### ISSUE TITLE
Can you add support for choosing a movie in the database?

### ISSUE THREAD

**Issue by marksev1** [k3yb0ardn1nja/mycroft-skill-kodi#3]
Hello, as the title implies :).

**Comment by digitaldoggo** [comment]
working on this now.

**Comment by marksev1** [comment]
Great! Happy new year!

**Comment by marksev1** [comment]
Is that new commit already ready to test?

**Comment by digitaldoggo** [comment]
It's not ready yet. Sorry about that. I was getting some old changes checked in before wiping an old development machine. I should have updated installation instructions that actually work and a very simple implementation of choosing a movie by name checked in very soon. In the initial simple form, the mechanism will find the first movie that contains the searched phrase and play it. I have started designing a much more complex approach that will be a lot more user friendly and also include consideration for TV Shows, but this will take some time to progress.

**Comment by marksev1** [comment]
Cool yeah (play, pause and stop work like a boss with your skill). Would be nice if it would be able to play stuff from Addons, but I know Kodi devs don't want to expose that stuff in the json-rpc api :-/.

**Comment by digitaldoggo** [comment]
I added a simple form of choosing movie from the movie library by partial/full name. Let me know how it works for you. There are many known limitations and issues with this current implementation that I am already planning on addressing, but please let me know any thoughts or comments.

I'll have to look into the Addons support. I'm not too familiar with them, but sounds like it will be trickier to get working. Maybe something another Addon could solve. ;)

You can invoke the intent to pick a movie by saying something like the following:
"start the movie Rolling Kansas"
"play Rolling Kansas"
"play the movie Rolling Kansas"

**Comment by digitaldoggo** [comment]
I'm working on further enhancing this by prompting the user for a choice, so they can be presented with multiple matching results or confirm that the movie that was found is what they were intending to play. With this will come better logic for searching as well. The current implementation is definitely crude and a lot of code cleanup and refactoring is in order, but it should work for many movies when you know the full name. By the way, thanks for the feedback!

**Comment by marksev1** [comment]
I shall give you feedback regarding the new addition in the next few days!

Thank you for your work so far, its cool  :).

**Comment by marksev1** [comment]
Soooo....it seems play, pause, stop still work :)
EDIT: Chosing movie works!!!! :D

Should I close it already and make a separate one for search videos in addons?

**Comment by digitaldoggo** [comment]
Nice! Glad to hear it's working for you. That sounds good to me. That will probably be something I'll investigate more once I get some better logic for the current movie search in there. I'll go ahead and close this one, since there is some basic functionality there, even if it is messy :)
